-- Reverte INC-SEG-1: restaura grants e desliga RLS apenas nas 26 tabelas que
-- estavam OFF antes desta migração (preserva as 10 que já tinham RLS ligado).
GRANT ALL ON ALL TABLES    IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES    TO anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon, authenticated;

ALTER TABLE public."_prisma_migrations" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.aluno DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.avaliacao DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificado DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.comunicado DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.comunicado_leitura DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.consentimento DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.curso DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.disciplina DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.evento DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.frequencia DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.grade_curricular DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.grade_disciplina DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.log_auditoria DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.material_biblioteca DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.matricula DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.mensagem_solicitacao DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.modelo_certificado DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.modulo_eixo DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.parcela DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.perfil DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.perfil_permissao DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.plano_pagamento DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.professor DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.turma DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuario DISABLE ROW LEVEL SECURITY;
